feat: set up automating deploy
ridatadiscoverycenter/buoy-viewer-nuxt pull request #41
Opened 2021-06-28 19:00 UTC by eldu

Draft for now. Checking to see if everything is okay!

2021-06-28 19:08 UTC, eldu commented
Not bad! Need to add in the environment variable for `VUE_APP_MAPBOX_ACCESS_TOKEN` for the demoic acid page to work though. 
<img width="800" alt="Screen Shot 2021-06-28 at 3 04 14 PM" src="https://user-images.githubusercontent.com/5270855/123690666-9da11780-d822-11eb-9445-692111499eac.png">

2021-06-29 19:57 UTC, eldu commented
It works now! 

Now i'm going to cache node modules

2021-06-29 21:33 UTC, mcmcgrath13 approved these changes
🚅

2021-06-29 21:33 UTC, mcmcgrath13 requested changes
I'm getting the firebase not found when going to https://riddc-buoy-explorer--pr41-feat-automate-deploy-ng54jjul.web.app/datasets/domoic-acid/

2021-06-30 03:07 UTC, mirestrepo commented
> I'm getting the firebase not found when going to https://riddc-buoy-explorer--pr41-feat-automate-deploy-ng54jjul.web.app/datasets/domoic-acid/

I get the page not found when I hit any sub-route directly, but it all works if I navigate from the main app... so its something with the router?

2021-06-30 03:16 UTC, mirestrepo commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
This makes me think this is why the direct routes are not working

2021-06-30 12:05 UTC, eldu commented
Hmm.. I too see that when we navigate from home that it works, but heading to the sub-route directly doesn't.

2021-06-30 12:14 UTC, eldu commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
Generate tries to create static html files. The purpose of this snippet of code was to exclude those routes from becoming static.

Though, consequently it seems like it has also excluded them as direct routes.

2021-06-30 12:23 UTC, mirestrepo commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
I think if they are not static routes they don't really exist ... and the rewrites in firebase config would have to handle to not get 404, but probably all it could do is send to home page. Why did not want the static html files generated for this?

2021-06-30 12:26 UTC, mirestrepo commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
@mcmcgrath13 do we need a hybrid `generate` + cloud functions solution as we have for ccv-website?

2021-06-30 12:33 UTC, mirestrepo commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
For the CCV website we generated all routes and @mcmcgrath13  wrapped the dynamic content in `<client-only>` like in [here](https://github.com/brown-ccv/ccv-website-nuxt/blob/c9cf9f1db4f3b27699204064e95f38d3280d3cfe/pages/index.vue#L19). Is that not something that would work here too?

2021-06-30 12:36 UTC, mirestrepo commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
Another thing that was bit messy but had worked, was to both use `generate` and `build` and the excluded routes would be rerouted to a cloud function that served the dynamic routes

2021-06-30 13:17 UTC, eldu commented on nuxt.config.js
> +    exclude: [/^\/datasets/],
I didn't want the static html files generated for this because of the API calls. I can try out using both `generate` and `build`. And I'll look more into the `client-only` tags.

2021-06-30 15:22 UTC, mcmcgrath13 commented on README.md
> +`yarn generate` configures our web application as a static web application. During this process, it generates every route as an HTML file and exports it to the `dist/` directory. This process raises
```suggestion
`yarn generate` configures our web application as a static web application. During this process, it generates every route as an HTML file and exports it to the `dist/` directory. This process raises a concern whether our dynamic content gets baked in/cached within the built site. 
```

2021-06-30 15:22 UTC, mcmcgrath13 commented on README.md
> +The theory for why the dynamic contect for this project continue to work is that we generally make our API calls in the store actions and retrieve data from the store. Nuxt isn't able to bake the res
```suggestion
The theory for why the dynamic content for this project continues to work is that we generally make our API calls in the store actions and retrieve data from the store. Nuxt isn't able to cache the results of these calls and keeps them as javascript. 
```

2021-07-02 13:02 UTC, mirestrepo approved these changes
🚀

2021-07-02 13:13 UTC, mcmcgrath13 approved these changes
🥇

2021-07-02 13:29 UTC, merged